gitHub.url: https://github.com

# or your GitHub Enterprise URL
#gitHub.url: https://my-ghe-url/api/v3


# your GitHub organization, for example myOrga in https://github.com/myOrga
organizationName: myOrga

publishExcludedRepositories: false

crawlAllBranches: false




